
-- CREATE DATABASE Test_DB;
-- DROP DATABASE test_d;

USE TEST_DB;

-- FOR THE CREATING THE TABLES  
CREATE TABLE STUDENTS(SNO INT(5),SNAME VARCHAR(15),MARKS INT(3));

-- GIVES THE OUTPUT OF SKELETON OF THE TABLE CREATED

DESCRIBE STUDENTS; 

-- INSERTING THE USERS INTO THE TABLES

INSERT INTO STUDENTS VALUES(1,'KIRAN',89); 

-- GIVES DATA OF THE TABLE

SELECT * FROM STUDENTS; 


CREATE DATABASE SAMPLES;

USE samples;

SELECT * FROM employees;

-- for sleecting the field name which has space the between them
 
SELECT `FIRST NAME` FROM employees;

SELECT `FIRST NAME` FNAME ,gender,Salary,Team FROM employees;


-- WHERE  - it is used for the Filtering the Records

USE SAMPLES;
SELECT * FROM employees;
SELECT * FROM EMPLOYEES WHERE SALARY>=130000;
SELECT * FROM EMPLOYEES WHERE SALARY=90000;
SELECT * FROM EMPLOYEES WHERE GENDER=MALE;
SELECT * FROM EMPLYEES WHERE TEAM=MARKETING;
SELECT distinct TEAM FROM EMPLOYEES;
SELECT distinct * FROM EMPLOYEES;

-- Using of the Loical Operators

USE SAMPLES;
SELECT * FROM employees;
SELECT GENDER FROM EMPLOYEES;
SELECT * FROM EMPLOYEES WHERE SALARY>=90000 AND GENDER='MALE';
SELECT * FROM EMPLOYEES WHERE SALARY>=80000 OR SALARY<=90000;
SELECT * FROM EMPLOYEES WHERE SALARY>=60000 AND TEAM='FINANCE';
SELECT * FROM EMPLOYEES WHERE NOT TEAM='FINANCE'; 


-- USING THE BETWEEN ,NOT BETWEEEN ,IN NOT IN OPERATORS
-- BETWEEN OPERATORS USED FOR THE GETTING values FROM TABLE IN THE GIVEN FOLLOWING RANGE 

SELECT * FROM EMPLOYEES WHERE SALARY BETWEEN 89000 AND 90000; 
SELECT * FROM EMPLOYEES WHERE SALARY NOT BETWEEN 60000 AND 90000;

-- IN OPERATOR WILL RETURN THE ROWS WHEN THE VALUES ARE MATCHING IN THE LIST
 
 SELECT * FROM EMPLOYEES WHERE SALARY IN (95000,50000,54043);
SELECT * FROM EMPLOYEES WHERE SALARY NOT IN (85000,50000,20000);

-- PATTERN MATCHING OPERATORS 
-- % - MANY CHARCTER
-- _ - SINGLE CHARCTER

-- WILL RETURN THE 'FIRST NAME' WHICH STARTS WITH THE 'S' CHARACTER 
SELECT * FROM EMPLOYEES WHERE `FIRST NAME` LIKE 'S%';    
SELECT * FROM EMPLOYEES WHERE `TEAM` LIKE 'E%';

-- RETURN THE FIRST NAME OR THE VALUES FROM THE COLUMN THAT END WITH MENTIONED CHARACTERS
SELECT * FROM EMPLOYEES WHERE `FIRST NAME` LIKE '%Y';
SELECT * FROM EMPLOYEES WHERE `TEAM` LIKE '%E'; 

-- RETURNS THE VALUES THAT START WITH 'S' AND END WITH 'Y' CHARACTERS
SELECT * FROM EMPLOYEES WHERE `FIRST NAME` LIKE 'S%Y';
SELECT * FROM EMPLOYEES WHERE `TEAM` LIKE 'S%E'; 

-- RETURN VALUES WHICH CONTAINS THE THIS CHARCTER EITHER AT BEGNING OR LAST OR IN THE MIDDLE
SELECT * FROM EMPLOYEES WHERE `FIRST NAME` LIKE '%M%';
SELECT * FROM EMPLOYEES WHERE `TEAM` LIKE '%N%';

-- RETURNS VALUE WHICH ENDS WITH Y AND ONE MORE CHARACTERS AT THE END
SELECT * FROM EMPLOYEES WHERE `FIRST NAME` LIKE '%Y_';
SELECT * FROM EMPLOYEES WHERE `TEAM` LIKE '%E_'; 

-- RETURNS THE VALUES WHOES LENGTH EQUALS TO THE UNIQUE DASHES
SELECT * FROM EMPLOYEES WHERE `FIRST NAME` LIKE '___';
SELECT * FROM EMPLOYEES WHERE `TEAM` LIKE '_____'; 

